[FEATURE] Auto create DB fields from TCA for type "input"
TYPO3-Documentation/TYPO3CMS-Reference-TCA pull request #1068
Opened 2024-06-19 12:56 UTC by linawolf

Releases: main
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/937

2024-06-19 14:17 UTC, fe-hicking commented on Documentation/ColumnsConfig/Type/Input/Index.rst
> +    then 255 chars :sql:`VARCHAR()` is used, :sql:`TEXT` for larger input fields.
```suggestion
    than 255 chars :sql:`VARCHAR()` is used, :sql:`TEXT` for larger input fields.
```

2024-06-19 14:17 UTC, fe-hicking commented on Documentation/ColumnsConfig/Type/Input/Index.rst
> +    then 255 chars :sql:`VARCHAR()` is used, :sql:`TEXT` for larger input fields.
We also need to describe this depends on the "max" attribute (cant do myself atm)

2024-06-19 14:17 UTC, fe-hicking commented on Documentation/ColumnsConfig/Type/Input/Index.rst
> +    do so by defining something specific in ext_tables.sql.
```suggestion
    do so by defining something specific in :file:`ext_tables.sql`.
```

2024-06-19 14:18 UTC, garvinhicking commented on Documentation/ColumnsConfig/Type/Input/Index.rst
> +    need an `ext_tables.sql` entry anymore. The Core now
```suggestion
    need an :file:`ext_tables.sql` entry anymore. The Core now
```

2024-06-20 06:30 UTC, froemken requested changes

2024-06-20 06:30 UTC, froemken commented on Documentation/ColumnsConfig/Type/Input/Index.rst
> +    creates this field automatically. For short input fields allowing less
Using the word "field" for a field within the TCA form is OK for me, but if we are talking about SQL and table columns I would prefer using "column". The second "field" in that row is OK for me as it relates to the TCE form.

```suggestion
    creates this column automatically. For short input fields allowing less
```

2024-06-20 07:54 UTC, froemken approved these changes

2024-06-20 08:53 UTC, merged