php classes
TYPO3-Documentation/TYPO3CMS-Reference-TCA pull request #391
Opened 2021-05-12 19:53 UTC by franzholz

2021-05-13 04:38 UTC, DavidBruchmann commented on Documentation/ColumnsConfig/Type/Passthrough/Index.rst
> +* A value sent to the
DataHandler is missing now?

2021-05-14 06:46 UTC, mbrodala requested changes

2021-05-14 06:46 UTC, mbrodala commented on Documentation/ColumnsConfig/Type/Passthrough/Index.rst
>    however never sends values.
```suggestion
* A value sent to the :php:`DataHandler` is kept as is and put into the database field. However, the default TYPO3 backend forms never send data for a `passthrough` field.
```

2021-05-14 06:46 UTC, mbrodala commented on Documentation/ColumnsConfig/Type/Passthrough/Index.rst
>  * Unlike none, type passthrough must have a database field.
```suggestion
* Unlike the field type `none`, the field type `passthrough` must have a database field.
```

2021-05-14 06:46 UTC, mbrodala commented on Documentation/ColumnsConfig/Type/Passthrough/Index.rst
> +* `FormEngine` does not render anything for passthrough types by default. But it can be combined with a custom
```suggestion
* The TYPO3 backend forms do not render anything for `passthrough` fields by default. But they can be combined with a custom
```

2021-05-14 06:46 UTC, mbrodala commented on Documentation/ColumnsConfig/Type/Passthrough/Index.rst
>    renderType to make it render something. A user type is better suited for such use cases, though.
```suggestion
  `renderType` to display something. A field of type `user` is better suited for such use cases, though.
```

2021-05-14 06:46 UTC, mbrodala commented on Documentation/ColumnsConfig/Type/Passthrough/Index.rst
> +* Type passthrough field values are usually not rendered at other places in the backend.
```suggestion
* Values of `passthrough` fields are usually not rendered at other places in the backend.
```

2021-05-14 06:46 UTC, mbrodala commented on Documentation/ColumnsConfig/Type/Passthrough/Index.rst
> +Typical usages of type passthrough is a field that only needs data evaluation on the `DataHandler` side, but
```suggestion
Typical usages of the field type `passthrough` is a field that only needs data evaluation on the `DataHandler` side, but
```

2021-05-14 06:58 UTC, mbrodala approved these changes

2021-05-14 06:59 UTC, merged