[DOCS] Add TCA path information
TYPO3-Documentation/TYPO3CMS-Reference-TCA pull request #520
Opened 2022-01-22 10:20 UTC by linawolf

Add information about where exactly the configuration is located in the TCA array

releases: main, 11.5

2022-01-22 16:30 UTC, nhovratov commented on Documentation/ColumnsConfig/CommonProperties/FieldControl.rst
> +   :Path: $GLOBALS['TCA'][$table]['columns'][$field]['config']
Should be inside `confval`

2022-01-22 16:36 UTC, nhovratov commented on Documentation/ColumnsConfig/Type/Group/Properties/FieldControl.rst
> +   :Path: $GLOBALS['TCA'][$table]['columns'][$field]['config']
Add it for insertClipboard too?

2022-01-22 16:45 UTC, nhovratov requested changes
Looks good, this gives a nice breadcrumb like orientation.
Found only one path outside the confal directive and another one, which can be added.
Besideds that +1 from me.

2022-01-22 16:49 UTC, nhovratov commented
Also, a "Fixes" can be added to the commit message for #404:

`Fixes: #404`

2022-01-23 09:51 UTC, marble approved these changes
I totally apreciate having that Path information. I'm not a hundred percent sure though the name will just stay "Path" if some built in functionatility is to be linked to that option. But this can surely be easily adapted to by some editorial measures.

2022-01-23 09:52 UTC, merged