Do not use "record type" as the title.
TYPO3-Documentation/TYPO3CMS-Reference-TCA pull request #536
Opened 2022-02-26 18:31 UTC by franzholz

I want to search for [$GLOBALS['TCA']['tx_news_domain_model_news']['ctrl']['type'].
It is only searchable if the title matches exactly the TCA array field name!

2022-02-27 08:51 UTC, linawolf commented
I don't see your point, you can search for "type" just fine:

![image](https://user-images.githubusercontent.com/48202465/155875461-e2c6481e-26d0-4b15-8035-0ed2754bb5f9.png)

2022-02-27 08:52 UTC, linawolf requested changes
No change is needed to make this searchable

2022-02-27 11:45 UTC, franzholz commented
When you have a TCA array in your PHP code, then you will open the Documentation page and search in the left menu for the entries by the key name of the TCA array. All other entries have their own key entry. Only this one has another title. This makes it complicate.

2022-03-02 16:53 UTC, linawolf approved these changes

2022-03-02 16:53 UTC, merged