add hint for mm table
TYPO3-Documentation/TYPO3CMS-Reference-TCA pull request #537
Opened 2022-02-26 22:21 UTC by franzholz

Helps a lot.

2022-02-27 09:03 UTC, linawolf requested changes

2022-02-27 09:03 UTC, linawolf commented on Documentation/ColumnsConfig/Type/Inline/Properties/ForeignSelector.rst
> +   is of type :ref:`select <columns-select>` and also has a :code:`foreign_table` defined. If the foreign table
You would  not use the MM table here directly but link to a foreign table using a MM relation stored in an intermediate table. Please rephrase

2022-03-10 22:27 UTC, nhovratov approved these changes

2022-03-15 07:25 UTC, linawolf approved these changes

2022-03-15 07:25 UTC, merged

2022-03-15 07:25 UTC, linawolf commented
releases: main, 11.5